SET IDENTITY_INSERT [dbo].[Marcas] ON

INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (6, N'Escolha a Marca')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (7, N'Acura')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (8, N'Agrale')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (9, N'Alfa Romeo')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (10, N'AM Gen')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (11, N'Asia Motors')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (12, N'ASTON MARTIN')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (13, N'Audi')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (14, N'Baby')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (15, N'BMW')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (16, N'BRM')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (17, N'Bugre')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (18, N'BYD')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (19, N'CAB Motors')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (20, N'Cadillac')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (21, N'Caoa Chery')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (22, N'Caoa Chery/Chery')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (23, N'CBT Jipe')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (24, N'CHANA')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (25, N'CHANGAN')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (26, N'Chrysler')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (27, N'Citroën')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (28, N'Cross Lander')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (29, N'D2D Motors')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (30, N'Daewoo')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (31, N'Daihatsu')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (32, N'Dodge')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (33, N'EFFA')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (34, N'Engesa')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (35, N'Envemo')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (36, N'Ferrari')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (37, N'Fiat')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (38, N'Fibravan')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (39, N'Ford')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (40, N'FOTON')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (41, N'Fyber')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (42, N'GEELY')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (43, N'GM - Chevrolet')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (44, N'GREAT WALL')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (45, N'Gurgel')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (46, N'GWM')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (47, N'HAFEI')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (48, N'HITECH ELECTRIC')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (49, N'Honda')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (50, N'Hyundai')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (51, N'Isuzu')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (52, N'IVECO')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (53, N'JAC')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (54, N'Jaguar')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (55, N'Jeep')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (56, N'JINBEI')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (57, N'JPX')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (58, N'Kia Motors')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (59, N'Lada')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (60, N'LAMBORGHINI')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (61, N'Land Rover')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (62, N'Lexus')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (63, N'LIFAN')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (64, N'LOBINI')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (65, N'Lotus')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (66, N'Mahindra')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (67, N'Maserati')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (68, N'Matra')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (69, N'Mazda')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (70, N'Mclaren')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (71, N'Mercedes-Benz')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (72, N'Mercury')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (73, N'MG')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (74, N'MINI')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (75, N'Mitsubishi')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (76, N'Miura')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (77, N'Nissan')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (78, N'Peugeot')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (79, N'Plymouth')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (80, N'Pontiac')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (81, N'Porsche')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (82, N'RAM')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (83, N'RELY')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (84, N'Renault')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (85, N'Rolls-Royce')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (86, N'Rover')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (87, N'Saab')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (88, N'Saturn')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (89, N'Seat')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (90, N'SHINERAY')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (91, N'smart')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (92, N'SSANGYONG')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (93, N'Subaru')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (94, N'Suzuki')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (95, N'TAC')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (96, N'Toyota')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (97, N'Troller')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (98, N'Volvo')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (99, N'VW - VolksWagen')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (100, N'Wake')
INSERT INTO [dbo].[Marcas] ([Id], [Nome]) VALUES (101, N'Walk')
SET IDENTITY_INSERT [dbo].[Marcas] OFF
